version: "3.2"

services:
    maven:
        build: maven/
        volumes: 
            - repo:/usr/local

    tomcat:
        image: tomcat:9.0-jdk8-adoptopenjdk-hotspot
        ports:
            8080:8080
        depends_on:
            - "maven"
        volumes: 
            - /usr/src/lesson7/boxfuse-sample-java-war-hello/target/*.war:/usr/local/tomcat/webapps/hello.war
            
volumes:
    repo: