# roles/buildserver/tasks/main.yml
---
- name: install packages
  apt: name={{item}} state=present
  become: yes
  with_items:
    - default-jdk
    - maven
    - git

- name: git clone project
  git:
    repo: '{{ git_repo_url }}'
    dest: '{{ git_repo_dest }}'
    clone: yes

- name: Running mvn clean
  shell: 'cd {{ git_repo_dest }} &&  mvn clean install'
  become: yes
  register: mvn_result

- name: "mvn clean task output"
  debug:
    var: mvn_result

- name: get .war-file from bulid-machine to master-machine
  fetch:
    src: '{{ war_file_path }}'
    dest: '{{ war_dest_in_master_vm }}'
    flat: yes